// Story Database
// Each story has its variables for chapters and logline

// Lima Story
const TheMechHunterLogline = "In a world ravaged by cybernetic horrors, the last Mech Hunter—a broken man haunted by the death of a loved one—wanders the ruins, seeking his end. But when the monsters that slaughtered humanity suddenly change, hunting not to infect but to capture, he discovers a mysterious girl who holds the key to their destruction. Now, he must choose between joining the dead or fighting for a future he never thought he’d see."
const TheMechHunterChapter1 = `It’s been 14 Years since the apocalypse started. The world is now a desolate wasteland, and the ruins of what once was can be seen with every turn. Survival wasn’t a given; it was a cause. The darkness belonged to them. The monsters—mechnoids—roamed with eyes like glowing embers, their forms hinted at only by the sound of grinding metal with every step. They were fast, faster than the wind, and they hunted because they must feed.

The road that once carried the hopes of men for salvation now stretches out into the abyss, having nothing more to offer than a slow tick to an uncalming end. A lone Hunter drives on this dusty road with his heavily armored rust bucket. He gulped down his last bottle of warm beer, ignoring the distant screams that echoed from the nearby abandoned facility, louder than the soft groans from his vehicle. “The noise is closer than I’d like”, he thought to himself, his only concern being the empty bottle. holding the stirring more tightly, as the wind whipped up dust against the windshield. “Why isn’t there any place left with good beer?” he muttered. The ’mechnoids’ as they are commonly called, aren’t a trouble for him anymore as he knows all he has to know about them, well, that’s what he tells himself. The armored suit he has on covers up to the back of his head, leaving only his face and hair exposed, with the name “MARKINE KRUST” engraved on his suit by the chest. That’s a name known by a lot of leftovers—who scavenge out for food, doing all they can to survive. He holds a necklace in his hand. Its cold metallic feel, sending a chill up his spine, brings back an unsettling memory from his past—one which he tries so much not to remember but dares not forget. It’s a long road, but he knows better than to be driving when night falls. “I’ve got to find a place to lay low and do it fast”, he muttered. “But first, I need a good beer,” he said, tossing the empty bottle to the back seat.

By dusk, he had found an old fuel station in the middle of the deserted wasteland far from the ruins of the city. Oh good, “I might even find some beer”, he muttered, parking his vehicle in a half way collapsed garage by the station, he stepped out of his vehicle with a Thimber shot in hand—'a gun created mainly for killing mechnoids', moving into the station building whose structure seems overly unstable, he sensed something move in the shadows at the far side of the station, "Those assholes", he said turning on his flash light as he entered the station, he soon arrived at a part of the building that seemed to once house a supermart, now it looks more like a junk pool, he moves through this pile of junk flashing is touch to see if he could find any beer, it's almost total night fall he has less time on his hands, he hears a sound from the corner, taking a closer look he sees some leftovers hiding there—” this place isn’t save” he said to them, walking away. He soon finds a glint of brown glass behind a rusted box. A beer bottle. He reached for it, but it was stuck. He yanked, and as he did, the box shifted, revealing a skeletal hand clamped around the bottle. He snatched it from the corpse, a wave of disgust hitting him as he saw a cluster of roaches scurrying inside the bottle. "What a waste, " he muttered, dropping the bottle to the floor.

Beep! That's from his watch, meaning it's total nightfall. "Oh shit, it's about time I return to the vehicle!" he exclaimed. There's no more time to search for beer; those monsters are coming. Stepping out of the supermart-like junk room, he heads for the door. Suddenly a mechnoid pounces at him, using is Thimber shot he blast it off—Those things are fast, hearing screams from the inner part of the building, he turned to look just to see something unusual about the mechnoids behavior “what the?” he exclaimed as his eyes widened in confusion “who cares, told them to be careful” he said, shooking the thought of his mind while running towards the exit door which seems closed—crashing through the door, his vehicle is on sight, looking to his right he sees a figure standing at the distance in the front yard of the station “a girl?” he said to himself. The girl doesn’t seem to be bothered by the mechnoids, it's like she’s not even there, and she was staring right at him, then, he noticed a mechnoid moving towards her. The man jumped at her to protect her from the coming mechnoid, then, using his Thimber shot, he blasted its head off. “What's wrong with you!” he exclaimed. She seemed shocked by his sudden action. As the number of mechnoids in the area was increasing rapidly, he, without a second thought, carried her on his shoulder and headed for the vehicle as she struggled getting off his shoulder. In a swift action, the man opened the vehicle, closed the door, and tossed her on the back seat. Immediately—he went to start the vehicle then drove out of the collapsing garage, as the structure begins to get more and more weaker due to the mechnoids climbing on to it, some also hop on his vehicle trying to capsize it, he soon shook them off as he drives out of the station into the night, keeping an eye on the girl at the back who his trying so hard to get the back door open or even break it, “it’s armored and even locked, so don’t bother” he said to her, by this time the vehicle as covered a far distance from the station—now in the middle of the deserted landscape.

He soon stopped the vehicle walking straight up to the girl—seeing him coming, she tried to attack him with her little fist but he grabbed her hand, “You’re quite strong” he said seeing as she was able to move his hand even though he gripped hers tight, she keeps hitting him on the chest with her other hand. “First you’ve to answer some questions” he said to her, pushing her on to the chair—” who the hell are you? and what were you doing out there? Answer me!” the man said, shouting at her, she sighed and said nothing. “you don’t want to talk huh!” the man exclaimed with slight rage—” I'm gonna ask you one more time, who the hell are you!” he exclaimed once again, then handcuffed her wrist to the chair’s arm, “ i’ll take that off, when you’re ready to talk” he said walking over to the driver’s seat. “you saw the beasts’ unusual actions, didn’t you?” she cried out to him. “beast?” the man said—as he stopped moving.  “I know a way to destroy all the beasts for good, and end the apocalypse,” said the girl, “Markins, I believe that’s your name, right? So what do you say?”. The man chuckled, “It’s Markine”, then turned, staring right into her eyes, “So you can talk, huh? Now answer me, who are you?” he said. His eyes, still fixed on hers, her face reminded him of someone he had lost a long time ago. holding the necklace in his hands more tightly, as the images of what he’d seen at the station—strange new behavior of the mechnoids—flashed through his mind.
<br> <b style="color: #ccc; font-family: Arial; font-size: 10px">Thanks for reading, The next chapter is coming soon...</b>`;
