// Story Database
// Each story has its own variables for chapters and logline

// Lima Story
const LimaLogline = "A young girl discovers a mysterious door in her grandmother's attic that leads to a world where dreams become reality. But when her nightmares start manifesting too, she must confront her deepest fears to save both worlds.";
const LimaChapter1 = "Lima had always loved her grandmother's attic. It was filled with treasures from around the world - exotic masks, ancient books, and strange artifacts that her grandmother had collected during her travels. But today, as she rummaged through an old cedar chest, she found something different. A small, ornate door, no bigger than a shoebox, with a golden key resting beside it.\n\nHer fingers trembled as she picked up the key. It was warm to the touch, almost as if it was alive. Without thinking, she inserted the key into the door's tiny lock. To her astonishment, the door swung open, revealing not the back of the chest, but a swirling vortex of colors.\n\n'This can't be real,' Lima whispered, but her curiosity overpowered her fear. She reached out a finger... and the vortex pulled her in.";
const LimaChapter2 = "Lima tumbled through the vortex, landing softly on a surface that felt like clouds. As she stood up, she found herself in a landscape straight out of her favorite childhood storybook. The trees had candy-colored leaves, the rivers flowed with liquid silver, and the sky was a perfect shade of violet.\n\n'Welcome to Oniria,' said a voice behind her. Lima turned to see a creature that looked like a cross between a rabbit and a dragon. 'I've been expecting you.'\n\n'Where am I?' Lima asked, her voice shaking.\n\n'This is the world of dreams,' the creature replied. 'Every night, when humans dream, they create pieces of this world. But something is wrong - the nightmares are growing stronger, and they're starting to break through to your world.'\n\nLima felt a chill run down her spine. She had been having terrible nightmares for weeks...";

// The Rat Taker Story
const TheRatTakerLogline = "In a plague-ridden medieval city, a mysterious figure known only as the Rat Taker moves through the shadows, collecting not just vermin but the darkest secrets of the nobility. When a young scribe uncovers his true purpose, she must decide whether to expose him or help him complete his deadly mission.";
const TheRatTakerChapter1 = "The stench of death hung heavy over the city of Valmire. The plague had taken hold with a vengeance, and the streets were littered with bodies waiting for the death carts. In the midst of this despair moved a figure wrapped in tattered gray robes, his face hidden behind a leather mask shaped like a rat's head.\n\nThey called him the Rat Taker.\n\nElara watched from the window of the scriptorium as the Rat Taker moved silently through the square. Unlike the other citizens who crossed themselves and looked away, she studied him. There was something deliberate in his movements, something that suggested his rounds were about more than just collecting dead rats.\n\n'Stop staring, girl,' Master Corvin hissed. 'That one's not to be trifled with.'\n\nBut Elara couldn't look away. As the Rat Taker passed beneath her window, he suddenly looked up, and through the eyeholes of his grotesque mask, she saw intelligence - and recognition.";
